name: secrets

on:
    push:
        branches:
            - main

jobs:
    build-test-publish:
        name: Publish to Docker
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: docker/build-push-action@v2
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: Superfuds/secrets
                  path: .
                  tags: ${{ github.sha }}, latest
